jenkins:
        image: docker.io/grafana/grafana
        ports:
           - "3000:3000"
        volumes:
           - "/var/lib/grafana:/var/lib/grafana"
           - "/etc/localtime:/etc/localtime"
        restart: always
